# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Me2_Business' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Me2_Business
  pod 'Cartography'
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'ImageSlideshow', '~> 1.8'
  pod 'ImageSlideshow/Kingfisher'
  pod 'NVActivityIndicatorView'
  pod 'Starscream', '~> 3.0.2'
  pod 'IQKeyboardManagerSwift'

end
